services:
  postgres:
    image: postgres:18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: student
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: